# Generated by Django 5.2.3 on 2025-07-26 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('page_section', models.CharField(blank=True, max_length=100)),
                ('original_image', models.ImageField(upload_to='original_images')),
            ],
            options={
                'verbose_name': 'Page Image',
                'verbose_name_plural': 'Page Images',
            },
        ),
    ]
