# Generated by Django 5.2.3 on 2025-07-27 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pageimages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pageimages',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='pageimages',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
