# Generated by Django 5.2.3 on 2025-08-19 05:02

import core.models
import django.core.validators
import django.db.models.deletion
import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_name_pageimages_title_pageimages_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='BikeInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=10)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('bike_img', imagekit.models.fields.ProcessedImageField(default=None, upload_to='upload/bikes')),
                ('status', models.CharField(choices=[('available', 'Available'), ('rented', 'Rented'), ('maintenance', 'Maintenance'), ('retried', 'Retried')], default='available', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Bicycle Instances',
                'ordering': ['bike_model__brand', 'bike_model__model', 'size'],
            },
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='bike',
        ),
        migrations.AddField(
            model_name='reservation',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='payment_status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='pageimages',
            name='original_image',
            field=models.ImageField(upload_to="images/", validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='pageimages',
            name='page_section',
            field=models.CharField(blank=True, help_text='e.g., homepage, about, bikes', max_length=100),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AddField(
            model_name='reservation',
            name='bike_instance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='core.bikeinstance'),
        ),
        migrations.CreateModel(
            name='BikeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(choices=[('road', 'Road'), ('mountain', 'Mountain'), ('electric', 'Electric'), ('trekking', 'Trekking')], max_length=50)),
                ('available_sizes', models.JSONField(default=list, help_text="Enter a list of available sizes for this model ['XS', 'S', 'M']", verbose_name='Available sizes')),
                ('specification', models.JSONField(blank=True, default=dict, null=True)),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Bicycle Models',
                'unique_together': {('brand', 'model', 'type')},
            },
        ),
        migrations.AddField(
            model_name='bikeinstance',
            name='bike_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='core.bikemodel'),
        ),
        migrations.DeleteModel(
            name='Bike',
        ),
    ]
