# Generated by Django 5.2.3 on 2025-08-19 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_bikeinstance_remove_reservation_bike_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='bike_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='core.bikeinstance'),
        ),
    ]
