# Generated by Django 5.2.3 on 2025-08-19 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_reservation_bike_instance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bikemodel',
            name='available_sizes',
        ),
    ]
