# Generated by Django 5.2.3 on 2025-08-20 05:07

import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_bikemodel_available_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikeinstance',
            name='bike_img',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='upload/bikes'),
        ),
        migrations.AlterField(
            model_name='bikeinstance',
            name='serial_number',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='bikeinstance',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('rented', 'Rented'), ('maintenance', 'Maintenance'), ('retired', 'Retired')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='bikemodel',
            name='model',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bikemodel',
            name='specification',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
