# Generated by Django 5.2.3 on 2025-08-22 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_bikeinstance_bike_img_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PageImages",
        ),
    ]
