# Generated by Django 5.2.3 on 2025-08-22 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_delete_pageimages"),
    ]

    operations = [
        migrations.AddField(
            model_name="bikemodel",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
