# Generated by Django 5.2.3 on 2025-08-25 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_bikemodel_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="bikemodel",
            name="model_description",
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
