# Generated by Django 5.2.3 on 2025-09-07 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='profile_pics/default_profile.webp', upload_to='profile_pics/'),
        ),
    ]
