# Generated by Django 5.2.3 on 2025-09-12 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_profile_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='StravaActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_id', models.BigIntegerField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('distance', models.FloatField()),
                ('total_elevation', models.FloatField()),
                ('start_date', models.DateTimeField()),
                ('activity_type', models.CharField(max_length=50)),
            ],
        ),
    ]
