# Generated by Django 5.2.3 on 2025-09-12 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_stravaactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='stravaactivity',
            name='summary_polyline',
            field=models.TextField(blank=True, null=True),
        ),
    ]
