# Generated by Django 5.2.3 on 2025-09-14 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_stravaactivity_summary_polyline'),
    ]

    operations = [
        migrations.AddField(
            model_name='stravaactivity',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
