# Generated by Django 5.2.3 on 2025-12-21 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_stravaactivity_updated_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
