# Generated by Django 5.2.3 on 2025-10-29 09:48

import cloudinary_storage.storage
import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_stravaactivity_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikeinstance',
            name='bike_img',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='upload/bikes'),
        ),
    ]
